In [30]:
comp=[f for f in range(60) if f<6]
comp

[0, 1, 2, 3, 4, 5]

# Exercice 1

In [31]:
t = np.arange(11)
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Exercice 2

In [9]:
t =np.linspace(0,1,5)
t

NameError: name 'np' is not defined

# Exercice 3


In [11]:
t = np.sum([2,5,13,4])
t

NameError: name 'np' is not defined

# Exercice 4

In [62]:
import numpy as np 

multt = np.array([12,4,6,8])
m = np.array([5,9,5,2])

mult =np.dot(t, m)






142

# Exercice 5

In [130]:
matrice = [12,3,6,6,8,34]
def f(matrice):

    liste_u = np.unique(matrice)
    r = list()
    for i in liste_u:
        c = np.sum(matrice==i)
        if c==1:
            r.append(i)
    return r
print(f(matrice))
    


[3, 8, 12, 34]


# Exercice 6


In [67]:
t = np.array([12,4,6,8,10,22,99])

mult =np.sort(t)
print("les éléments ont ordre croissant")
mult

array([ 4,  6,  8, 10, 12, 22, 99])

# Exercice 7

In [15]:
import numpy as np
t = np.array([12,4,6,8,10,22,99])

moyenne = np.mean(t)
mediane = np.median(t)
ecart_type = np.std(t)


print("Moyenne:", moyenne)
print("Médiane:", mediane)
print("Écart type:",ecart_type)






Moyenne: 23.0
Médiane: 10.0
Écart type: 31.49149545058611


In [13]:
import numpy as np

# Exercice 8

In [14]:
t = np.array([12,4,6,8,10,22,99])
1*(t>5)




    


array([1, 0, 1, 1, 1, 1, 1])

# Exercice 9

In [124]:

a= np.random.randint(0,10,size=(3,3))
a

array([[5, 4, 6],
       [5, 2, 9],
       [5, 6, 2]])

# fonction

In [2]:
def nommax(x) :
    max = x[0]
    for indice in range(1,len(x)) :
        if x [indice] > max :
            max = x[indice]
            return max
        x[1,3,5,3]
        nommax(x)
print("hello")

        
    

hello
